title: Randhi Putra
email: hey@randhi.pro
description: "Senior Software Developer specializing in Fullstack & AI Product Engineering"
url: "https://randhi.pro"
baseurl: ""
timezone: Asia/Bangkok

permalink: /blog/:title/
markdown: kramdown

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
